spring:
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  context-path: /golden